version: '2'

services:
  web:
    restart: always
    build: ./web
    depends_on:
      - db
    ports:
     - "80:80"
     - "443:443"
  front:
    restart: always
    build: ./front
    ports:
     - "3000:3000"
     - "3001:3001"
     - "4200:4200"
     - "8080:8080"
    volumes:
     - ./front:/tmp/cache
    depends_on:
     - web
  db:
    restart: always
    hostname: mysqlserver
    image: hypriot/rpi-mysql
    ports:
     - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: test_db
      MYSQL_USER: test_user
      MYSQL_PASS: test_password
    volumes:
      - my-datavolume:/var/lib/mysql
volumes:
  my-datavolume:
